source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!


##Flutter工程路径
#flutter_application_path = 'my_flutter_module'
##读取 podhelper.rb 的Ruby代码在当前目录执行
#eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

flutter_application_path = 'flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target ‘YWNativeDemo’ do

  install_all_flutter_pods(flutter_application_path)

#轮播组件
#pod 'FSPagerView'

pod 'Then'


post_install do |installer|
  flutter_post_install(installer)
  
    installer.generated_projects.each do |project|
       project.targets.each do |target|
         

	      target.build_configurations.each do |config|
               config.build_settings["DEVELOPMENT_TEAM"] = ""
               #config.build_settings["CODE_SIGN_IDENTITY"] = ""
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

            end
       end
     end
    
end

end


